# Generated by Django 3.2.18 on 2023-03-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fgapi', '0003_auto_20230311_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
