# Generated by Django 3.2.18 on 2023-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapi', '0005_rename_title_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
